//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.03 at 12:06:01 PM CEST 
//


package fr.imag.adele.fede.workspace.as.initmodel.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.imag.adele.fede.workspace.as.initmodel.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.imag.adele.fede.workspace.as.initmodel.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CLinkDescription }
     * 
     */
    public CLinkDescription createCLinkDescription() {
        return new CLinkDescription();
    }

    /**
     * Create an instance of {@link CAttType }
     * 
     */
    public CAttType createCAttType() {
        return new CAttType();
    }

    /**
     * Create an instance of {@link CValuesType }
     * 
     */
    public CValuesType createCValuesType() {
        return new CValuesType();
    }

    /**
     * Create an instance of {@link CPages }
     * 
     */
    public CPages createCPages() {
        return new CPages();
    }

    /**
     * Create an instance of {@link CBindingLink }
     * 
     */
    public CBindingLink createCBindingLink() {
        return new CBindingLink();
    }

    /**
     * Create an instance of {@link CItemType }
     * 
     */
    public CItemType createCItemType() {
        return new CItemType();
    }

    /**
     * Create an instance of {@link CActionContributor }
     * 
     */
    public CActionContributor createCActionContributor() {
        return new CActionContributor();
    }

    /**
     * Create an instance of {@link CItemDescription }
     * 
     */
    public CItemDescription createCItemDescription() {
        return new CItemDescription();
    }

    /**
     * Create an instance of {@link COperationParamItemDescription }
     * 
     */
    public COperationParamItemDescription createCOperationParamItemDescription() {
        return new COperationParamItemDescription();
    }

    /**
     * Create an instance of {@link CViews }
     * 
     */
    public CViews createCViews() {
        return new CViews();
    }

    /**
     * Create an instance of {@link COperation }
     * 
     */
    public COperation createCOperation() {
        return new COperation();
    }

    /**
     * Create an instance of {@link COperationParamAttributeRef }
     * 
     */
    public COperationParamAttributeRef createCOperationParamAttributeRef() {
        return new COperationParamAttributeRef();
    }

    /**
     * Create an instance of {@link CLinkType }
     * 
     */
    public CLinkType createCLinkType() {
        return new CLinkType();
    }

    /**
     * Create an instance of {@link COperationParamOther }
     * 
     */
    public COperationParamOther createCOperationParamOther() {
        return new COperationParamOther();
    }

    /**
     * Create an instance of {@link CView }
     * 
     */
    public CView createCView() {
        return new CView();
    }

    /**
     * Create an instance of {@link COperationParamLinkRef }
     * 
     */
    public COperationParamLinkRef createCOperationParamLinkRef() {
        return new COperationParamLinkRef();
    }

    /**
     * Create an instance of {@link CExtBiding }
     * 
     */
    public CExtBiding createCExtBiding() {
        return new CExtBiding();
    }

    /**
     * Create an instance of {@link COperationParamString }
     * 
     */
    public COperationParamString createCOperationParamString() {
        return new COperationParamString();
    }

    /**
     * Create an instance of {@link CCadse }
     * 
     */
    public CCadse createCCadse() {
        return new CCadse();
    }

    /**
     * Create an instance of {@link CItem }
     * 
     */
    public CItem createCItem() {
        return new CItem();
    }

    /**
     * Create an instance of {@link COperationParamLinktypeRef }
     * 
     */
    public COperationParamLinktypeRef createCOperationParamLinktypeRef() {
        return new COperationParamLinktypeRef();
    }

    /**
     * Create an instance of {@link CMenuAction }
     * 
     */
    public CMenuAction createCMenuAction() {
        return new CMenuAction();
    }

    /**
     * Create an instance of {@link CCadseRef }
     * 
     */
    public CCadseRef createCCadseRef() {
        return new CCadseRef();
    }

    /**
     * Create an instance of {@link CField }
     * 
     */
    public CField createCField() {
        return new CField();
    }

    /**
     * Create an instance of {@link CExtensionItemType }
     * 
     */
    public CExtensionItemType createCExtensionItemType() {
        return new CExtensionItemType();
    }

    /**
     * Create an instance of {@link TreeView }
     * 
     */
    public TreeView createTreeView() {
        return new TreeView();
    }

    /**
     * Create an instance of {@link COperationEx }
     * 
     */
    public COperationEx createCOperationEx() {
        return new COperationEx();
    }

    /**
     * Create an instance of {@link COperationType }
     * 
     */
    public COperationType createCOperationType() {
        return new COperationType();
    }

    /**
     * Create an instance of {@link COperationParamItemRef }
     * 
     */
    public COperationParamItemRef createCOperationParamItemRef() {
        return new COperationParamItemRef();
    }

    /**
     * Create an instance of {@link CLink }
     * 
     */
    public CLink createCLink() {
        return new CLink();
    }

    /**
     * Create an instance of {@link CAction }
     * 
     */
    public CAction createCAction() {
        return new CAction();
    }

    /**
     * Create an instance of {@link COperationParam }
     * 
     */
    public COperationParam createCOperationParam() {
        return new COperationParam();
    }

    /**
     * Create an instance of {@link CMetaAttribute }
     * 
     */
    public CMetaAttribute createCMetaAttribute() {
        return new CMetaAttribute();
    }

    /**
     * Create an instance of {@link CPage }
     * 
     */
    public CPage createCPage() {
        return new CPage();
    }

    /**
     * Create an instance of {@link COperationParamBoolean }
     * 
     */
    public COperationParamBoolean createCOperationParamBoolean() {
        return new COperationParamBoolean();
    }

    /**
     * Create an instance of {@link CConstraint }
     * 
     */
    public CConstraint createCConstraint() {
        return new CConstraint();
    }

    /**
     * Create an instance of {@link COperationParamItemtypeRef }
     * 
     */
    public COperationParamItemtypeRef createCOperationParamItemtypeRef() {
        return new COperationParamItemtypeRef();
    }

}
