//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.13 at 01:47:36 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://fr.imag.adele/fede/workspace/model")
package fr.imag.adele.fede.workspace.as.initmodel.jaxb;
